# Generated by Django 4.2.1 on 2023-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='active',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
